#pragma once

#include <vector>
#include <string>

enum SCRIPT_TYPE
{
	ASTEROIDBELTSCRIPT,
	BLACKHOLESCRIPT,
	BOSSBULLETSCRIPT,
	BOSSEMPTYSCRIPT,
	BOSSPLANETS,
	BOSSSCRIPT,
	BOSSSHILED,
	BULLETPARTICLESCRIPT,
	BULLETSCRIPT,
	CAMERAMOVESCRIPT,
	CAMERASCRIPT,
	MISSILESCRIPT,
	MONSTERSCRIPT,
	PLANET_LOTATING,
	PLAYERSCRIPT,
	DEBUGSCRIPT,
	FADING,
	HITPOSTSCRIPT,
	HYPERLOOPSCRIPT,
	HYPERLOOPSCRIPT_JUPITER,
	HYPERLOOPSCRIPT_MARS,
	HYPERLOOPSCRIPT_NEPTUNE,
	HYPERLOOPSCRIPT_SATURN,
	HYPERLOOPSCRIPT_URANUS,
	METEOSCRIPT,
	MINIBOSSBULLETSCRIPT,
	MINIBOSSSCRIPT,
	MONSTERBULLETSCRIPT,
	END,
};

using namespace std;

class CScript;

class CScriptMgr
{
public:
	static void GetScriptInfo(vector<wstring>& _vec);
	static CScript * GetScript(const wstring& _strScriptName);
	static CScript * GetScript(UINT _iScriptType);
	static const wchar_t * GetScriptName(CScript * _pScript);
};
